version: '3.5'
services:
  the-eye-app: &base-container
    container_name: the-eye-app
    image: the-eye-image
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../:/opt/app
    depends_on:
      - the-eye-psql
      - the-eye-rabbitmq
    links:
      - the-eye-psql:postgresql
      - the-eye-rabbitmq:rabbitmq
    environment:
      APPLY_MIGRATIONS: 1
      DEV_SERVER: 1
      DATABASE_HOST: postgresql
      LOAD_STATIC_FILE: 1
      DJANGO_SETTINGS_MODULE: the_eye.settings
    ports:
      - "8080:8080"

  the-eye-psql:
      image: postgres:13-alpine
      container_name: the-eye-psql
      restart: unless-stopped
      environment:
        LC_ALL: C.UTF-8
        POSTGRES_USER: app
        POSTGRES_PASSWORD: randomP@ssword!
        POSTGRES_DB: the_eye
      volumes:
          - pgdata:/var/lib/postgresql/data/
  
  the-eye-celery:
    <<: *base-container
    container_name: the-eye-celery
    ports:
      - "5555:5555"
    entrypoint: bash -c "celery -A the_eye worker -c 8 -l INFO"

  the-eye-rabbitmq:
    container_name: the-eye-rabbitmq
    image: rabbitmq:3.8-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=app
      - RABBITMQ_DEFAULT_PASS=R@bbitmqPass!

volumes:
  pgdata:
